# Site settings
title: Aaron's Website!
description: Aaron's Website!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aaron Robson
user_description: I am a postgraduate Computer Game Engineering MSc student with a passion for games development.
user_title: Computer Games Engineering MSc student
email: aaronrobson19@hotmail.co.uk
twitter_username: Robson1Aaron
github_username:  GeordieGinge
youtube_username:  Aaron Robson
linkedin_username:  Aaron Robson


exclude: ['package.json', 'src' , 'node_modules']
