# Site settings
title: Aaron's Website!
description: Aaron's Website!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aaron Robson
user_description: I am a postgraduate Computer Game Engineering MSc student with a passion for games development currently I am working on a group based project that involves us making a game from scratch, engine and all. My role in the group is the head of networking, and I am currently researching/working with ENet. I primarily focus on engine work but I am hoping to gain more experience in the different fields of games development as well.
user_title: Computer Games Engineering MSc student
email: aaronrobson19@hotmail.co.uk
twitter_username: Robson1Aaron
github_username:  GeordieGinge
youtube_username:  Aaron Robson
linkedin_username:  Aaron Robson


exclude: ['package.json', 'src' , 'node_modules']
