# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aaron Robson
user_description: I am a postgraduate Computer Game Engineering MSc student with a passion for games development and I want to improve my skills and gain vital experience in a working business environment. I primarily focus on engine work but I am hoping to gain more experience in the different fields of the games industry as well.
user_title: Computer Games Engineering MSc student
email: aaronrobson19@hotmail.co.uk
twitter_username: Robson1Aaron
github_username:  GeordieGinge
youtube_username:  Aaron Robson
linkedin_username:  Aaron Robson


exclude: ['package.json', 'src' , 'node_modules']
